name: Deploy static content to Pages

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Determine environment name
        id: determine-env
        run: |
          if [ ${{ github.ref }} = 'refs/heads/main' ]; then
            echo "::set-output name=env-name::github-pages"
          elif [ ${{ github.ref }} = 'refs/heads/develop' ]; then
            echo "::set-output name=env-name::develop"
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          environment_name: ${{ steps.determine-env.outputs.env-name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
